### ISSUE TITLE
Increase portability by publishing CSS instead of SASS

### ISSUE THREAD

**Issue by cfatorNSS** [matteocng/react-flag-icon-css#4]
Not everyone uses SASS.  Would be nice if the published output was in a more universal form and let the consuming developer make any app specific transformations to SASS, LESS etc.  You can still use SASS inside the package.

**Comment by matteocng** [comment]
Hello @cfatorNSS, thanks for your suggestion, I agree with removing the dependency from sass. flag-icon-css distributes .css too, so that is easy. Internally, I would like to switch the simple SASS styles to PostCSS (and a few plugins if needed), rename them to .css and their folder to 'styles'. Then using a CLI task they can be compiled to plain, uncompressed CSS and published to NPM.
